---
title: "Debt to Income Ratio"
---

```{r, echo=F}
options(scipen = 6)
knitr::opts_chunk$set(cache=FALSE, fig.height=3, fig.width = 7, comment=NULL, eval=T, tidy=F, width=80, message= FALSE, echo= FALSE, warning = FALSE)
```


```{r, child="_preamble.Rmd"}
```


```{r, child="_nofilter.Rmd"}
```

### Debt-to-Income Ratio  

Lending Club sets a upper limit of 0.5 debt to income ratio.  There are a few points in the dataset above that limit but they are very clearly outliers.  For this analysis, I've set those values at the limit of 50.


```{r}
LoanData[which(LoanData$dti>50),"dti"]<- 50

ggplot(LoanData) + 
    aes(dti, group=Class, colour=Class) + 
    geom_density()+ 
    labs(title="Distribution of DTI by default status") + 
    theme_LC()
```

```{r}
a<- ggplot(LoanData %>% mutate(Year= format(issue_d,"%Y")))
a<- a + aes(x=Year, y=dti)
a<- a + geom_violin(fill = "grey80", draw_quantiles = c(0.5))
a<- a + labs(title="Distribution of DTI by Year")
a<- a + theme_LC()
a
rm(a)
```

```{r, fig.height=8}
a<- ggplot(LoanData %>% mutate(Year= format(issue_d,"%Y")))
a<- a + aes(x=Year, y=dti, fill=grade)
a<- a + geom_violin(draw_quantiles = c(0.5))
a<- a + facet_wrap(~grade, ncol=2)
a<- a + labs(title="Distribution of DTI by year and grade")
a<- a + theme_LC()
a
rm(a)
```

```{r, fig.height=6}
# b<- LoanData %>%
#     group_by(grade, Class) %>%
#     summarize(write_mean= mean(dti))
# 
a<- ggplot(LoanData %>% mutate(Year= format(issue_d,"%Y")))
a<- a + aes(x=Class, y=dti, fill=Class)
a<- a + facet_wrap(~Year)
a<- a + geom_violin(draw_quantiles = c(0.5))
a<- a + labs(title="Distribution of DTI by default status and year")
a<- a + theme_LC()
a
rm(a)
```     
