---
title: "Research Questions"
subtite: "How to optimize the profit to risk ratio?"
---



## Objective

The objective of this reseach is to determine the strategy which optimizes the ratio of investor income to risk.  An investment can be viewed as a fair exchange transaction:  The investor seeks to receive a return on their capital so purchases a potential cash flow which includes interest payments. I say potential cash flow because it is not guaranteed that the borrower will not default.  The investor's payment for this interest income is the amount of risk they accepte that the borrower will default on the loan causing the investor to lose the invested captial and the opportunity cost of lost interest income.  Higher interst rates, then, will require them to accept greater amounts of risk.

The initial interest rate (price) is set by LC's determination of the investor's risk.  On the secondary market, the yield on the loan includes the interest payments from LC's credit scoring model plus the seller's markup adjustment for their perceived risk score.  There may also be market factors at work setting prevailing yield amounts.  In order to optimize the ratio of income to risk, I will have to find areas in these two pricing models which overptice borrower's risk.  The interest rate is set higher than the default risk warrants. 

On the journey towards the over arching objective, I have these interim questions to answer:


1. Can we identify over priced default risk by using more than just the intuitive features such as FICO score and debt-to-income and thereby increase profitability?

2. Can we determine the market price of a loan after issuance (secondary marke)?  Use the listings on the secondary market to develop a pricing guide or tool? 
    - Can market price be determined from the secondary market listings?  Take regular downloads of the market and look for time until sale.  
    - Can the typical consumer price their loans to market value? Is there a random walk around the true price point for given attributes/risk factors? Is there an opportunity for arbitration?

2. Can we estimate the value a loan on the secondary market and build a pricing model such that: Value = PV of cash flow discounted for default risk and market data asymmetry.  Influences are expected cash flow driven by defualt rates/ survival analysis; present value driven by investor requirements or IRR; general discount as the buyer doesn't know why you are selling so feels lack of trust (constant?).

3. Can we leverage the latest fraud research to identify over stated income and replace with an estimated true amount to feed the model?

4. How does Basel II Probability of default definitions apply?  Can that research and precendents be applied?
