---
title: "Model Review"
output: html_document
bibliography: bibliographies.bib
csl: snippet/journal-of-finance.csl
vignette: >
    %\VignetteIndexEntry{Exploratory Analysis- Loan Amount} 
    %\VignetteEngine{knitr::rmarkdown}\usepackage[utf8]{inputenc}
---

> NOTE: this file is being used to capture my notes while reading through the models.  Once I've read and digested, I'll turn this into a cohesive summary. 


## Lending club - predicting loan outcomes
[@mdlOrourke]

Data Period: 2007-2011  
Notes:  

- Divided characteristics into two categories: those about the loan and about the borrower.  Did not formally define the groups.
- Filtered out late loans leaving just fully paid, defaulted, and charged off.  Defaulted and charge-off loans combined into a single group.  

Analysis:    

- Filtered characteristics by reading the descriptions in the data dictionary. Criteria seems to be intuition and the level of documentation.  There was no analysis for correlation with outcome to support decisions. 
- Chargeoffs focused in higher interest rates, fully paid more evenly distributed  
- distribution of loans by grade  
- 36 vs 60 month loan chargeoff rates  
- Current.Account.Ratio  number of open credit lines divided by total number f accounts 
    
Modeling:  

- Decision tree- The AUC from this model was 0.68 but only 60 charge-off loans were correctly identified. After resampling to increase the proportion of charge-offs, the confusion matrix increased to identifying 700 of the 1100 charge-offs.
- Logistic Regression- AUC: 0.697.  Confusion matrix ID'd 730 of the 1100 charge-offs.
- Ensembled- Using bagging
    
Analysis review:
The exploratory analysis was not particularly insightful.  The author did not document the basis for several key decisions such as which variables to include/exclude or why he chose the specific algorithms. The charts were not styled beyond the ggplot defaults. 

<hr>
## Changes in lending club underwriting
[@mdlWu1]

Data: June 2015 - May 2016  

Notes: 

- Response to LC's quarterly earnings release, where LC announced changes in underwriting 
- Used commentary from LC's 10-Q.

Analysis:  

- Scatter plot of average DTI for D grade loans by issue date.  The plot attempts to show that less high DTI loans have been issued since LC changed its underwriting in late April 2016. The article hypothesizes that the loans are removed from the direct pay program.  Direct pay requires the loan proceeds be paid directly to the borrower's existing debts.
- Scatter plot of number of inquiries by issue date for F and G grade loans. The plot shows that in the past month there have been less loans with a high number of previous inquiries. 


<hr>
## Analysis of Lending Club's data
[@mdlDarren]  

Data: through June 2015.  

Data cleaning:   

- Removed loans where the : 
    - policy code is not 1 meaning they are new products not yet publically available. 
    - high FICO score was 0 meaning the data was not valid.
    - Revolving credit utilization data was missing
    - Low FICO score was less than 600.  Per the new underwriting policy, borrowers with a score less than 600 aren't allowed to receive a loan. 
- New features engineered: 
    - Year from the issue date
    - Bins or brackets based on FICO scores 
    - Buckets for the:
        - years, quarthers, and months of issue dates 
        - number of inquries in the past 6 months
        - DTI
        - Revolving balance
- Filtered to remove loans that have matured. 
- Grouped statuses into 2 categories: debt and purchases. Credit card and debt consolidation were grouped into the debt category and all others to purchases.
- Simplified the number of delinquencies by threshold +/- 2 delinquiries in 2 years.
- Simplified the number of public records by threshold +1.

Analysis: 

- FICO score by loan grade showing that most subgrades have average FICO scores within a 10 point range. The initial conclusion is that FICO score doesn't have a linear relationship with the loan grade. Expanded to show density around the average score by year which shows the densities started with a tight distribution around the mean and then widened with time. The ending conclusion is that LC initially relied heavily on the credit score in the loan grading model and then loosened their reliance on it. 
- Look at several variables for a relationship with defaults, loan grades, and fico scores: 
    - Home ownership -- 'mortgage' defualted at 11.5% and 2% less than other values. No analysis by loan grades. 
    - Purpose -- 'education' and 'small business' have higher charge off rates but education is a very small population. At the total population level, the FICO score does not reflect the higher risk.    
    - Revolving balance & employment length -- no/minimal link to default.  A bump in the charge-off ratio when the employment length is NA which is in contrast to the higher average credit score. 
    - Number of delinquencies
    - Number of open accounts 
    - Debt to Income 
    - Public Records
    - Age of credit history 
    - Revolving utilization
    - Annual income 
    - Inquiries in 6 months 
    - Geography 


Model Review: Most comprehensive analysis yet.


<hr>

- [@socialLender]  
- [@mdlDavenport]  
- [@mdlWu2]  
- [@mdlCashorali]  
- [@mdlToth]  
- [@mdlMistry]  
- [@mdlPolena]  
- [@mdlKaggle]  
- [@mdlDavis]  
- [@mdlPatierno]  
- [@mdlTsai]
- [@mdlSummers]


# References